name: Compile MoneroMiner to WebAssembly

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código-fonte do seu repositório (incluindo submódulos se houver)
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # 2. Instala as dependências de compilação do Linux (CMake e Make)
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: '3.1.50'
        cache-key: 'actions-v3-key'

    # 4. Executa a checagem das versões para garantir que o emcc está ativo
    - name: Verify Emscripten Installation
      run: |
        emcc -v
        em++ -v

    # 5. Roda o comando Make usando o seu Makefile reestruturado para WebAssembly
    - name: Compile Project via Makefile
      run: |
        make distclean
        make -j$(nproc) 
        

    # 6. Salva os arquivos miner.js e miner.wasm gerados para você baixar no painel do GitHub
    - name: Upload WebAssembly Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: monerominer-wasm-dist
        path: |
          bin/*
        retention-days: 7
